import { r2ImageUrl } from './helper';
import baseLogo from 'data-base64:@/assets/images/base-logo-in-blue.svg';
import suiLogo from 'data-base64:@/assets/images/sui-sui-logo.svg';
import solanaLogo from 'data-base64:@/assets/images/solana.svg';

export const images = {
  logoInComingSoon: r2ImageUrl('logoInComingSoon.svg'),
  popupTop: r2ImageUrl('popup-top.png'),
  popupBottom: r2ImageUrl('popup-bottom.png'),
  iconPolygonChain: r2ImageUrl('polygon-matic-logo.svg'),
  notFoundToken: r2ImageUrl('not-found.png'),
  avatarDefaultProfile: r2ImageUrl('avatar-default-profile.svg'),
  backgroundProfileSetting: r2ImageUrl('background-profile-setting.png'),
  iconSettingLight: r2ImageUrl('icon-setting-light.svg'),
  iconEditDark: r2ImageUrl('icon-edit-dark.svg'),
  iconSuccess: r2ImageUrl('success.svg'),
  iconFailed: r2ImageUrl('failed.svg'),
  iconVoteStats: r2ImageUrl('icon-vote-stats.svg'),
  iconWarningDark: r2ImageUrl('warning-dark.svg'),
  iconShowKey: r2ImageUrl('show-key.svg'),
  iconHideKey: r2ImageUrl('hide-key.svg'),
  iconGoBack: r2ImageUrl('go-back.svg'),
  buttonQuest: r2ImageUrl('button-quest.png'),
  logoGradient: r2ImageUrl('logoGradient.png'),
  iconEthereum: r2ImageUrl('Ethereum.svg'),
  iconShill: r2ImageUrl('icon-shill.svg'),
  iconMetamask: r2ImageUrl('metamask.svg'),
  iconAccordion: r2ImageUrl('icon-accordion.svg'),
  iconSettingDark: r2ImageUrl('setting.svg'),
  iconClose: r2ImageUrl('icon-close.svg'),
  iconImportWallet: r2ImageUrl('import-wallet.svg'),
  iconDeposit: r2ImageUrl('deposit.svg'),
  logoUnion: r2ImageUrl('chain-zoom-union.png'),
  iconLogout: r2ImageUrl('logout.svg'),
  iconCopyDark: r2ImageUrl('copy-dark.svg'),
  iconPorfolio: r2ImageUrl('icon-porfolio.svg'),
  iconAlert2: r2ImageUrl('icon-alrert-2.svg'),
  iconStar2: r2ImageUrl('icon-star-2.svg'),
  iconSetting: r2ImageUrl('icon-setting.svg'),
  logoDark: r2ImageUrl('logo-dark.svg'),
  logoLight: r2ImageUrl('logo-light.svg'),
  iconFreshWalletDark: r2ImageUrl('fresh-wallet-dark.svg'),
  iconFreshWalletLight: r2ImageUrl('fresh-wallet-light.svg'),
  iconTopHolderDark: r2ImageUrl('top-holder-dark.svg'),
  iconTopHolderLight: r2ImageUrl('top-holder-light.svg'),
  iconTopPnlDark: r2ImageUrl('top-pnl-dark.svg'),
  iconTopPnlLight: r2ImageUrl('top-pnl-light.svg'),
  iconSearch: r2ImageUrl('icon-search.svg'),
  iconChatDark: r2ImageUrl('icon-chat.svg'),
  iconAvatar: r2ImageUrl('avatar.svg'),
  logoTokenDefault: r2ImageUrl('logo-token-default.png'),
  iconCopy: r2ImageUrl('icon-copy.svg'),
  iconTwitter: r2ImageUrl('icon-twitter.svg'),
  iconTelegram: r2ImageUrl('icon-telegram.svg'),
  iconWebsite: r2ImageUrl('icon-website.svg'),
  iconYes: r2ImageUrl('yes.svg'),
  iconCancel: r2ImageUrl('cancel.svg'),
  iconSecurityActive: r2ImageUrl('iconSecuActive.svg'),
  iconItemSecurity: r2ImageUrl('icon-item-security.svg'),
  iconAlert: r2ImageUrl('icon-alert.svg'),
  iconStar: r2ImageUrl('icon-star.svg'),
  iconCheck: r2ImageUrl('icon-check.svg'),
  iconLike: r2ImageUrl('icon-like.svg'),
  logoBlur: r2ImageUrl('blur-logo.svg'),
  iconConnectWallet: r2ImageUrl('icon-connect-wallet.svg'),
  iconFlame: r2ImageUrl('icon-flame.svg'),
  rightEnable: r2ImageUrl('right-enable.svg'),
  leftDisable: r2ImageUrl('left-disable.svg'),
  logo2: r2ImageUrl('logo2.svg'),
  qr: r2ImageUrl('qr.svg'),
  buttonPoint: r2ImageUrl('buttonPoint.png'),
  hand: r2ImageUrl('hand.svg'),
  rank: r2ImageUrl('rank.svg'),
  checked: r2ImageUrl('checked.svg'),
  buttonClaimPoint: r2ImageUrl('button-claim-point.png'),
  bgPopupClaimed: r2ImageUrl('bg-popup-claimed.svg'),
  bgPopupClaimed2: r2ImageUrl('bg-popup-claimed-2.png'),
  spinBlur: r2ImageUrl('spin-blur.svg'),
  trophy: r2ImageUrl('trophy.svg'),
  gift: r2ImageUrl('gift.svg'),
  bgLuckySpin: r2ImageUrl('bg-lucky-spin.svg'),
  wheelPoint: r2ImageUrl('wheel-point.svg'),
  center: r2ImageUrl('center.svg'),
  bgWithBorder: r2ImageUrl('bg-with-border.svg'),
  fullBgWheel: r2ImageUrl('full-bg-wheel.svg'),
  infoCircle: r2ImageUrl('info-circle.svg'),
  allBgLuckySpin: r2ImageUrl('all-bg-lucky-spin.svg'),
  baseLogo,
  suiLogo,
  solanaLogo,
};
